version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt-get update && apt-get install -y cmake git
      - checkout
      - run: ls; ls ~/project
      - run: cd ~/project && mkdir build && cd build
      - run: cmake ..
      - run: make
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
